const { execFileSync } = require('node:child_process');
const { createServer } = require('node:http');
const fs = require('node:fs');
const { chromium } = require('/tmp/yappr-csp/node_modules/playwright');
const repo='/tmp/yappr-csp', base='4105c5d1c914f5d0838619da93c3b8d28b4a780e';
const head=execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim();
const script='https://static.cloudflareinsights.com/beacon.min.js';
const records={};
for(const [label,rev] of [['before',base],['after',head]]) {
 const source=execFileSync('git',['show',`${rev}:app/layout.tsx`],{cwd:repo,encoding:'utf8'});
 records[label]={revision:rev,policy:source.match(/content="(default-src[^"]+)"/)[1]};
}
const server=createServer((req,res)=>{
 const label=req.url.slice(1), entry=records[label];
 if(!entry){res.writeHead(404);res.end();return;}
 res.setHeader('Content-Type','text/html; charset=utf-8');
 res.end(`<!doctype html><html><head><meta http-equiv="Content-Security-Policy" content="${entry.policy}"><style>body{font:18px system-ui;background:#f4f6f8;color:#192230;padding:36px}main{max-width:1040px;padding:30px;background:white;border:1px solid #d9e0e5;border-radius:16px}h1{font-size:28px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#edf0f4;padding:16px;font-size:16px}.status{padding:20px;border-radius:8px;font-weight:600}.blocked{background:#ffebe9;color:#a22320}.loaded{background:#dafbe1;color:#116329}small{color:#4c5b70}</style></head><body><main><small>Yappr PR #406 · browser diagnostic fixture · ${label}</small><h1>Cloudflare Insights script loading</h1><p>Exact layout revision: <code>${entry.revision}</code></p><p>Script: <code>${script}</code></p><div id="status" class="status">Testing…</div><h2>Browser observation</h2><pre id="event"></pre><h2>script-src from app/layout.tsx</h2><pre>${entry.policy.split(';').find(s=>s.trim().startsWith('script-src'))}</pre><p>This diagnostic runs the policy extracted from the committed layout. The external script response is a harmless local stub; Chromium still enforces CSP. This is not an application screenshot.</p></main><script>const s=document.getElementById('status'),e=document.getElementById('event');window.result={};document.addEventListener('securitypolicyviolation',v=>{if(v.blockedURI.includes('cloudflareinsights')){window.result={outcome:'blocked',effectiveDirective:v.effectiveDirective,blockedURI:v.blockedURI,disposition:v.disposition};s.textContent='BLOCKED — the browser refused the injected script';s.className='status blocked';e.textContent=JSON.stringify(window.result,null,2)}});const script=document.createElement('script');script.src=${JSON.stringify(script)};script.onload=()=>{window.result={outcome:'loaded',event:'HTMLScriptElement load',src:script.src};s.textContent='LOADED — the browser accepted the script';s.className='status loaded';e.textContent=JSON.stringify(window.result,null,2)};script.onerror=()=>{if(!window.result.outcome){window.result={outcome:'network-error'};e.textContent=JSON.stringify(window.result)}};document.body.append(script);</script></body></html>`);
});
(async()=>{await new Promise(r=>server.listen(4187,'127.0.0.1',r));const browser=await chromium.launch();try{for(const label of ['before','after']){const page=await browser.newPage({viewport:{width:1280,height:900}});await page.route(script,route=>route.fulfill({contentType:'application/javascript',body:'window.insightsProbeLoaded=true;'}));await page.goto(`http://127.0.0.1:4187/${label}`);await page.waitForFunction(()=>Boolean(window.result?.outcome));records[label].observed=await page.evaluate(()=>window.result);if(records[label].observed.outcome!==(label==='before'?'blocked':'loaded'))throw new Error(JSON.stringify(records[label]));await page.screenshot({path:`/tmp/yappr-csp-proof/${label}.png`});await page.close();}fs.writeFileSync('/tmp/yappr-csp-proof/results.json',JSON.stringify(records,null,2));console.log(JSON.stringify(records));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
