const fs=require('fs');const assert=require('assert/strict');const {execFileSync}=require('child_process');const receipts=()=>JSON.parse(execFileSync('node',['/tmp/yappr-onboarding-qa/read-qa93-receipt.mjs'],{cwd:'/tmp/yappr-onboarding-qa',env:{...process.env,NETWORK:'devnet'}}).toString().trim().split('\n').at(-1));const{run,expect}=require('/tmp/yappr-qa-browser.cjs');const dir='/tmp/yappr-qa93-review-evidence';fs.mkdirSync(dir,{recursive:true});const r={base:'cf0efbc10b8757137063113ebbd2061e8b87d8f7',head:execFileSync('git',['rev-parse','HEAD'],{cwd:'/Users/pasta/.t3/worktrees/yappr/dm-local-unread-state'}).toString().trim(),at:new Date().toISOString(),messages:[],sides:[]};const save=()=>fs.writeFileSync(dir+'/result.json',JSON.stringify(r,null,2));
run(async open=>{
 const warm=await open(66,'/messages/?startConversation=HMqf6LRJ4uxwjQqNYdJXrENQNFSuLbB91hfj7j8zy8P3');await expect(warm.page.getByPlaceholder('Type a message...')).toBeVisible({timeout:60000});await warm.page.waitForTimeout(3000);await warm.context.close();r.receiptBefore=receipts();save();
 const before=await open(66,'/settings/?section=privacy');const after=await open(66,'/settings/?section=privacy');await after.page.goto('http://127.0.0.1:3296/devnet/settings/?section=privacy');after.base='http://127.0.0.1:3296/devnet';
 for(const v of [before,after]){await v.page.setViewportSize({width:1440,height:1000});const sw=v.page.getByRole('switch',{name:'Read Receipts',exact:true});await expect(sw).toHaveAttribute('aria-checked','true',{timeout:60000});await sw.click();await expect(sw).toHaveAttribute('aria-checked','false');}
 const sender=await open(67,'/messages/?startConversation='+before.identity);await expect(sender.page.getByPlaceholder('Type a message...')).toBeVisible({timeout:60000});
 async function send(label){const text=label+' '+Date.now();r.messages.push(text);save();await sender.page.getByPlaceholder('Type a message...').fill(text);await sender.page.getByRole('button',{name:'Send message',exact:true}).click();await expect(sender.page.getByPlaceholder('Type a message...')).toHaveValue('',{timeout:60000});return text}
 const message=await send('QA93 review read without receipts');
 for(const [side,v,count] of [['before',before,1],['after',after,0]]){fs.mkdirSync(dir+'/'+side,{recursive:true});await v.page.goto(v.base+'/messages/');const row=v.page.getByRole('button').filter({hasText:message});await expect(row).toBeVisible({timeout:60000});await v.page.waitForTimeout(2000);await expect(row.locator('div.bg-yappr-500.text-white.text-xs')).toHaveText('1');await row.click();await expect(v.page.getByText(message,{exact:true}).last()).toBeVisible();await expect(row.locator('div.bg-yappr-500.text-white.text-xs')).toHaveCount(0);await v.page.waitForTimeout(500);await v.page.screenshot({path:dir+'/'+side+'/opened.png'});await v.page.reload();await expect(row).toBeVisible({timeout:60000});await v.page.waitForTimeout(2000);await expect(row.locator('div.bg-yappr-500.text-white.text-xs')).toHaveCount(count);await v.page.waitForTimeout(500);await v.page.screenshot({path:dir+'/'+side+'/reloaded.png'});r.sides.push({side,unreadAfterReload:await row.locator('div.bg-yappr-500.text-white.text-xs').allTextContents(),row:await row.innerText()});save();}
 async function senderRefresh(){await sender.page.reload();const row=sender.page.getByRole('button').filter({hasText:r.messages.at(-1)});await expect(row).toBeVisible({timeout:60000});await row.click();await expect(sender.page.getByText(r.messages.at(-1),{exact:true}).last()).toBeVisible();await sender.page.waitForTimeout(1000)}
 await senderRefresh();const bubble=sender.page.getByText(message,{exact:true}).last().locator('../..');await expect(bubble.getByText('· Read',{exact:true})).toHaveCount(0);r.receiptAfterDisabled=receipts();assert.deepEqual(r.receiptAfterDisabled,r.receiptBefore);r.disabledReceipt='Fresh sender has no Read on the new message; actual public receipt document unchanged';await sender.page.screenshot({path:dir+'/sender-receipts-off.png'});save();
 const newMessage=await send('QA93 new incoming message');await after.page.reload();const newRow=after.page.getByRole('button').filter({hasText:newMessage});await expect(newRow).toBeVisible({timeout:60000});await after.page.waitForTimeout(2000);await expect(newRow.locator('div.bg-yappr-500.text-white.text-xs')).toHaveText('1');r.newIncoming='New incoming message increments unread to1; old locally read message remains excluded';await after.page.screenshot({path:dir+'/after/new-incoming.png'});await newRow.click();await expect(after.page.getByText(newMessage,{exact:true}).last()).toBeVisible();await expect(newRow.locator('div.bg-yappr-500.text-white.text-xs')).toHaveCount(0);await after.page.reload();await expect(newRow).toBeVisible({timeout:60000});await after.page.waitForTimeout(2000);await expect(newRow.locator('div.bg-yappr-500.text-white.text-xs')).toHaveCount(0);save();
 await after.page.goto(after.base+'/settings/?section=privacy');await after.page.getByRole('switch',{name:'Read Receipts',exact:true}).click();const onMessage=await send('QA93 receipts enabled');await after.page.goto(after.base+'/messages/');const onRow=after.page.getByRole('button').filter({hasText:onMessage});await expect(onRow).toBeVisible({timeout:60000});await onRow.click();await expect(after.page.getByText(onMessage,{exact:true}).last()).toBeVisible();await expect(onRow.locator('div.bg-yappr-500.text-white.text-xs')).toHaveCount(0);await senderRefresh();await expect(sender.page.getByText(onMessage,{exact:true}).last().locator('../..').getByText('· Read',{exact:true})).toBeVisible({timeout:60000});r.receiptAfterEnabled=receipts();assert.ok(r.receiptAfterEnabled[0].updatedAt>r.receiptBefore[0].updatedAt);r.enabledReceipt='Fresh sender sees Read on newly opened message with receipts enabled; public receipt update timestamp increased';await sender.page.screenshot({path:dir+'/sender-receipts-on.png'});r.cleanup='Three dedicated QA messages remain; no ordinary DM delete control. After context Read Receipts restored true; before context disposed.';save();console.log(JSON.stringify(r));await before.context.close();await after.context.close();await sender.context.close();
}).catch(e=>{r.error=e.message;save();console.error(e.message);process.exitCode=1});
